name: Building and Using artifact
on: push
jobs:
  build_artifact:
   runs-on: ubuntu-latest
   steps:
    - name: create file
      run: echo 'Hello World' > file.txt
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
       name: file
       path: file.txt
  
  print_artifact:
   runs-on: ubuntu-latest
   needs: build_artifact
   steps:
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
       name: file
       path: .
    - name: print artifact
      run: cat file.txt



